behaviors:
  Bow:
    trainer_type: sac
    hyperparameters:
      batch_size: 256
      buffer_size: 500000
      learning_rate: 0.0003
      learning_rate_schedule: constant
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
#      curiosity:
#        gamma: 0.99
#        strength: 0.02
#        encoding_size: 256
#        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 12000
    threaded: true
